### ISSUE TITLE
과제 평가

### ISSUE THREAD

**Issue by munyeol-Yoon** [marioahn/node_post_mall#1]
게시글 목록 전체 조회 API 에서 인자 req 는 사용하지 않는 것으로 보입니다 _ 처리를 해주어 확실하게 하면 좋을 것 같습니다.

snake_case 를 사용하셨는데 그 이유가 궁금합니다.

댓글 생성에서 Object key 를 통한 에러처리를 하셨는데 어떤 이유에서 사용하였는지 궁금합니다.

 댓글 수정 부분에서 updateOne 에 $set 을 사용하고 안하고의 차이가 무엇인가요?

dotenv 를 사용하셨는데 스키마의 index 에 URL 을 노출시킨 이유가 무엇인가요?

스키마의 versionKey 가 무엇인지 궁금합니다. 

이상 전체적으로 에러코드 부분이 정말깔끔하게 처리하여 배운점이 많았습니다!!

**Comment by marioahn** [comment]
이슈 남겨주셔서 감사합니다!

**1. 게시글 목록 전체 조회 API 에서 인자 req 는 사용하지 않는 것으로 보입니다 _ 처리를 해주어 확실하게 하면 좋을 것 같습니다.**
- `(req, res)` -> req 대신, 언더바 처리해서 아예 안 썼다는 걸 명확하게
-> `router.get("/", async (_, res) `

** 2. snake_case 를 사용하셨는데 그 이유가 궁금합니다 -> ex)'_postId'**
- 문제(명세서)는 'find_one' 스네이크케이스로 작성, but 나는  'postId'같이 카멜케이스로 작성
- 문제(명세서 등)에 적힌대로 변수명 작성법 등 통일 시키기
- 또한, `_(언더바)변수명`은 의미가 굉장히 많고 중요해서, 어떤 의도가 있지 않고 서는 안 쓰는 게 좋다
- ex) `_변수명`: 어떠한 의도가 있으니 함부로 수정 하지 말라는 뜻이 있는 경우도 있다

**3. 댓글 생성에서 Object key 를 통한 에러처리를 하셨는데 어떤 이유에서 사용하였는지 궁금합니다.**
- 굳이 아래 방식으로 키값 가져올 필요 없는 듯하다
-  `if (Object.keys(req.params).length < 1 || !user || !password)`
- req.params가 비어있는 가에 대한 코드인데, 오히려 길어진 느낌
- 수정: `if (!req.params || !user || !password)`
 
**4. 댓글 수정 부분에서 updateOne 에 $set 을 사용하고 안하고의 차이가 무엇인가요?**
- `{ $set: { password, content } }`
- 안 써도 똑같이 작동 하지만, set을 쓰는 것을 권장한다
- ( https://stackoverflow.com/questions/59539881/how-does-set-update-work-in-nodejs )
-> [$set] is a mongo update operator. Using the $set operator you can change the value for a field or even assign new fields to a document.

**5. dotenv 를 사용하셨는데 스키마의 index 에 URL 을 노출시킨 이유가 무엇인가요?**
- dotenv 사용법을 제대로 숙지하지 못한 상태에서 사용하였고, 코드를 수정하엿다
- app.js ->
*const dotenv = require('dotenv') // dotenv가져오기
*dotenv.config() // dotenv를 사용하겠다는 코드 - 여기에 적용하겠다
*const port = process.env.PORT; // 여길 추가
- .env 파일 생성 -> (숨겨두는 목적이므로, .env 파일자체도 숨겨져있다)
* .env는 전부다 대문자로 써야한다
* 따라서, 카멜케이스가 아닌 스네이크케이스로 쓴다
* EX) PORT_STAR
*PORT = 3000 <- 작성 (.env에 이렇게 적어둠 = .env에 숨겨둔다 (app.js에서 빼고)

**6. 스키마의 versionKey 가 무엇인지 궁금합니다.**
- 참조사이트: https://mongoosejs.com/docs/guide.html#versionKey
- versionkey를 쓰면 __v를 없앨 수 있다
- { __v: 0, name: 'mongoose v3' } => { _somethingElse: 0, name: 'mongoose v3' }
